- name: mysql configuration
  hosts: mysql
  become: yes
  vars: 
    mysql_root_password: ExpenseApp@1
    login_host: mysql.devops1289.online
  tasks:
  - name: ansible to install bpymysql
    ansible.builtin.pip:
      name:
      - PyMySQL
    executable: pip3.9

  - name: install MySQL Server
    ansible.builtin.package:
    name: mysql-server
    state: present

  - name: started mysql server
    ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"      
    ignor_errors: True
    register: mysql_info

  - name: print the mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true        
